- key: cls_telegraph
  name: 财联社(快讯镜像)
  url: https://rsshub.app/cls/telegraph
  keep: false
  consec_fail: 0
  last_ok: 2025-09-25T08:49:17+0800
  last_error: null
  ok: true
- key: ft_cn
  name: FT中文
  url: https://www.ftchinese.com/rss/news
  keep: false
  consec_fail: 0
  last_ok: 2025-09-25T08:49:17+0800
  last_error: null
  ok: true
- key: investing
  name: 英为财情
  url: https://www.investing.com/rss/121899.rss
  keep: false
  consec_fail: 0
  last_ok: 2025-09-25T08:49:17+0800
  last_error: null
  ok: true
- key: jiemian
  name: 界面新闻
  url: https://a.jiemian.com/index.php?m=article&a=rss
  keep: false
  consec_fail: 0
  last_ok: 2025-09-25T08:49:17+0800
  last_error: null
  ok: true
