- key: ft_cn
  name: FT中文
  url: https://www.ftchinese.com/rss/news
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

- key: jiemian
  name: 界面新闻
  url: https://a.jiemian.com/index.php?m=article&a=rss
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

- key: sina_hot
  name: 新浪财经(热榜)
  url: https://rss.sina.com.cn/roll/finance/hot_roll.xml
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

- key: cls_telegraph
  name: 财联社(快讯镜像)
  url: https://rsshub.app/cls/telegraph
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

# 下面这些是补充（RSSHub 镜像，若 3 次失败脚本会自动删除）
- key: caixin_latest
  name: 财新(镜像)
  url: https://rsshub.app/caixin/latest
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

- key: wallstreetcn
  name: 华尔街见闻(镜像)
  url: https://rsshub.app/wallstreetcn/news/global
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

- key: stcn
  name: 证券时报(镜像)
  url: https://rsshub.app/stcn/news
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

- key: yicai_brief
  name: 第一财经(镜像)
  url: https://rsshub.app/yicai/brief
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

- key: csrc
  name: 中国证监会(镜像)
  url: https://rsshub.app/csrc/news
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

- key: cninfo_latest
  name: 巨潮公告-最新(镜像)
  url: https://rsshub.app/cninfo/announcement/latest
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

- key: 36kr_flash
  name: 36氪快讯(镜像)
  url: https://rsshub.app/36kr/newsflashes
  keep: false
  consec_fail: 0
  last_ok:
  last_error:

