- key: investing
  name: 英为财情
  url: https://www.investing.com/rss/121899.rss
  keep: false
  consec_fail: 0
  last_ok: 2025-12-09T13:46:04+0800
  last_error: null
  ok: true
- key: jiemian
  name: 界面新闻
  url: https://a.jiemian.com/index.php?m=article&a=rss
  keep: false
  consec_fail: 0
  last_ok: 2025-12-09T13:46:04+0800
  last_error: null
  ok: true
