name: daily-push

on:
  schedule:
    # GitHub Actions 用 UTC，需要把北京时间换算成 UTC
    # 北京 09:50  -> UTC 01:50
    # 北京 11:20  -> UTC 03:20
    # 北京 15:05  -> UTC 07:05
    - cron: "50 1 * * 1-5"
    - cron: "20 3 * * 1-5"
    - cron: "05 7 * * 1-5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector (news_pipeline)
        env:
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
          JUHE_KEY: ${{ secrets.JUHE_KEY }}
        run: |
          python news_pipeline.py

      - name: Push strategy (opening)
        if: startsWith( github.event.schedule, '50 1' )
        env:
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          python daily_push_qwen.py --slot open

      - name: Push strategy (noon)
        if: startsWith( github.event.schedule, '20 3' )
        env:
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          python daily_push_qwen.py --slot noon

      - name: Push strategy (close)
        if: startsWith( github.event.schedule, '05 7' )
        env:
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          python daily_push_qwen.py --slot close
