name: Collector and Push

on:
  workflow_dispatch:
  schedule:
    # 工作日白天每小时跑一次采集 + 推送（UTC 1-8点 ~ 北京 09:00-16:00）
    - cron: '0 1-8 * * 1-5'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
      JUHE_KEY: ${{ secrets.JUHE_KEY }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      SCKEY: ${{ secrets.SCKEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SPAN_DAYS: "3"

      # ↓↓↓ 新增：源白名单/黑名单/自定义
      # 说明：使用 “sid” 值（见 news_pipeline.py 源表）
      # 仅用这些源（留空=不启用白名单）
      RSS_WHITELIST: ""
      # 排除这些源（留空=不启用黑名单）
      RSS_BLACKLIST: ""
      # 追加自定义 RSS 源：用分号分隔多条，每条格式：名称|id|url
      # 例如： "某行业媒体|myind|https://example.com/rss;国际监管|regint|https://rsshub.app/xxx"
      RSS_EXTRA: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Show holdings
        run: |
          echo "holdings.json content:"
          if [ -f holdings.json ]; then cat holdings.json; else echo "holdings.json not found"; fi

      - name: Run collector (news_pipeline.py)
        run: python news_pipeline.py

      - name: Run pusher (daily_push_qwen.py)
        run: |
          if [ -f "daily_push_qwen.py" ]; then
            python daily_push_qwen.py || true
          else
            echo "daily_push_qwen.py not found, skip push."
          fi

      - name: Upload artifacts (outputs + logs)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: news-artifacts
          if-no-files-found: ignore
          path: |
            briefing.txt
            news_all.csv
            keywords_used.txt
            qwen_keywords.txt
            sources_used.txt
            sources_health.json
            errors.log
