name: Collector and Push

on:
  workflow_dispatch:
  schedule:
    # 工作日白天每小时跑一次采集 + 推送（UTC 1-8点 ~ 北京 09:00-16:00）
    - cron: '0 1-8 * * 1-5'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
      JUHE_KEY: ${{ secrets.JUHE_KEY }}
      QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
      SCKEY: ${{ secrets.SCKEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      # 采集器可选项
      USE_GOOGLE: "0"        # 默认关Google。如需开，改为 "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Show holdings
        run: |
          echo "holdings.json content (masked weights):"
          python - << 'PY'
import json, pathlib
p=pathlib.Path('holdings.json')
print(p.read_text('utf-8') if p.is_file() else 'holdings.json not found')
PY

      - name: Run collector (news_pipeline.py)
        run: python news_pipeline.py

      - name: Run pusher (daily_push_qwen.py)
        run: python daily_push_qwen.py

      - name: Upload artifacts (outputs + logs)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: news-artifacts
          if-no-files-found: ignore
          path: |
            briefing.txt
            news_all.csv
            keywords_used.txt
            qwen_keywords.txt
            sources_used.txt
            errors.log
            logs-and-history-*.zip
