name: 每日投资建议

on:
  schedule:
    # 每天早上 8 点（UTC 时间 = 北京时间 - 8 小时）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 支持手动触发

jobs:
  run-daily-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          pip install requests pyyaml

      - name: 执行每日推送脚本
        run: python daily_push_qwen.py
