name: Collector and Push

on:
  workflow_dispatch:
  schedule:
    # 北京时间 08:00 → UTC 00:00
    - cron: '0 0 * * 1-5'
    # 北京时间 11:00 → UTC 03:00
    - cron: '0 3 * * 1-5'
    # 北京时间 13:30 → UTC 05:30
    - cron: '30 5 * * 1-5'
    # 北京时间 15:00 → UTC 07:00
    - cron: '0 7 * * 1-5'

permissions:
  contents: write  # 允许把 sources.yml 的 ok/失败计数回写

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      # 推送与关键词扩展所需
      QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
      JUHE_KEY: ${{ secrets.JUHE_KEY }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      MEDIASTACK_KEY: ${{ secrets.MEDIASTACK_KEY }}
      SCKEY: ${{ secrets.SCKEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      BARK_KEY: ${{ secrets.BARK_KEY }}

      # 采集器的可调参数（保持原值）
      SPAN_DAYS: 3


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Show holdings
        run: |
          echo "holdings.json content (masked weights):"
          python - << 'PY'
          import json, pathlib
          p = pathlib.Path('holdings.json')
          if p.is_file():
            msg = p.read_text('utf-8')
          else:
            msg = 'holdings.json not found'
          print(msg)
          PY

      - name: Run collector (news_pipeline.py)
        run: python news_pipeline.py

      - name: Run pusher (daily_push_qwen.py)
        run: |
          if [ -f "daily_push_qwen.py" ]; then
            python daily_push_qwen.py || true
          else
            echo "daily_push_qwen.py not found, skip push."
          fi

      - name: Upload artifacts (outputs + logs)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: news-artifacts
          if-no-files-found: ignore
          path: |
            briefing.txt
            keywords_used.txt
            qwen_keywords.txt
            sources_used.txt
            errors.log
            logs-and-history-*.zip
            sources.yml

      - name: Commit back updated sources.yml (ok/失败次数回写)
        if: always()
        run: |
          if git diff --quiet --exit-code sources.yml; then
            echo "No sources.yml changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add sources.yml
            git commit -m "chore: auto-update sources.yml"
            git push
          fi
