name: A-share Intraday Advice

on:
  # 北京时间 09:50 / 11:20 / 15:05
  schedule:
    - cron: '50 1 * * 1-5'
    - cron: '20 3 * * 1-5'
    - cron: '5 7 * * 1-5'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      TUSHARE_TOKEN:      ${{ secrets.TUSHARE_TOKEN }}
      JUHE_KEY:           ${{ secrets.JUHE_KEY }}
      QWEN_API_KEY:       ${{ secrets.QWEN_API_KEY }}
      SCKEY:              ${{ secrets.SCKEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - run: python holdings_tracker.py
      - run: python news_pipeline.py   # 每次都刷新 briefing.md
      - run: python daily_push_qwen.py

      - name: Upload logs & history
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-and-history-${{ github.run_number }}
          path: |
            pipeline.log
            holdings_history.csv
            keywords_used.txt
          retention-days: 30
