name: 每日投资建议

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 时间每天 00:00 执行（北京时间 08:00）
  # 手动运行按钮（可选）
  workflow_dispatch:

jobs:
  run-daily-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          pip install requests pyyaml

      - name: 执行每日推送脚本
        run: python daily_push_qwen.py
        env:
          SCKEY: ${{ secrets.SCKEY }}
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
