name: Daily Investment Push
on:
  schedule:
    - cron: '55 23 * * *'        # 北京时间 07:55
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    concurrency:
      group: daily-push
      cancel-in-progress: false

    env:
      TUSHARE_TOKEN:  ${{ secrets.TUSHARE_TOKEN }}
      ALPHA_KEY:      ${{ secrets.ALPHA_KEY }}
      FINNHUB_KEY:    ${{ secrets.FINNHUB_KEY }}
      JUHE_KEY:       ${{ secrets.JUHE_KEY }}
      QWEN_API_KEY:   ${{ secrets.QWEN_API_KEY }}
      SCKEY:          ${{ secrets.SCKEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Track holdings
        run: python holdings_tracker.py

      - name: Aggregate news
        run: python news_pipeline.py --days 1 --max 40

      - name: Generate & push advice
        run: python daily_push_qwen.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-log
          path: pipeline.log
          retention-days: 7
          
      - name: Upload holdings log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: holdings-log
          path: holdings_log.csv
          retention-days: 7

      - name: Upload holdings history
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: holdings-history
          path: holdings_history.csv
          retention-days: 30

