name: 每日推送投资建议

on:
  schedule:
    - cron: '30 0 * * *'  # 每天 UTC 00:30 = 北京时间 08:30
  workflow_dispatch:      # 支持手动触发

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 执行脚本
        env:
          SCKEY: ${{ secrets.SCKEY }}
        run: python daily_push.py
