name: 每日投资建议

on:
  push:
    branches:
      - main

jobs:
  run-daily-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          pip install requests pyyaml

      - name: 执行脚本
        run: python daily_push_qwen.py
